# Generated by Django 6.0.1 on 2026-01-13 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChocolateProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('price', models.PositiveIntegerField(default=0)),
                ('existence', models.CharField(choices=[('have got', 'Bor'), ('have_not_got', "Yo'q")], max_length=100)),
                ('product_type', models.CharField(choices=[('dark', 'Dark'), ('milk', 'Milk'), ('white', 'White'), ('ice_cream', 'Ice Cream')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('price', models.PositiveIntegerField(default=0)),
                ('chocolate_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.chocolateproduct')),
            ],
        ),
    ]
